# To boot the app run the following:
# docker-compose run Daovous-AI
version: '3.9'

services:
  ai-retriever:
    depends_on:
      - redis
    build: ./
    env_file:
      - .env
    tty: true
    environment:
      MEMORY_BACKEND: ${MEMORY_BACKEND:-redis}
      REDIS_HOST: ${REDIS_HOST:-redis}
    volumes:
      - ./:/app
    networks:
      - daovous-net
    ports:
      - 8090:8090
  redis:
    image: 'redis/redis-stack-server:latest'
    ports:
      - 6379:6379
    networks:
      - daovous-net
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
      interval: 2s
      timeout: 1m30s
      retries: 5
      start_period: 5s

networks:
  daovous-net:
    name: daovous-net
    external: true

volumes:
  redis_data: